import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("academy", "routes/academy.tsx"),
  route("membership", "routes/membership.tsx"),
  route("impact", "routes/impact.tsx"),
  route("shop", "routes/shop.tsx"),
  route("book", "routes/book.tsx"),
  route("farm", "routes/farm.tsx"),
  route("stories", "routes/stories.tsx"),
  route("events", "routes/events.tsx"),
  route("virtual", "routes/virtual.tsx"),
  route("journal", "routes/journal.tsx"),
  route("give", "routes/give.tsx"),
  route("community", "routes/community.tsx"),
  route("legacy", "routes/legacy.tsx"),
  route("podcast", "routes/podcast.tsx"),
  route("refer", "routes/refer.tsx"),
  route("wisdom", "routes/wisdom.tsx"),
  route("command", "routes/command.tsx"),
  route("ndis", "routes/ndis.tsx"),
  route("visual", "routes/visual.tsx"),
  route("calm", "routes/calm.tsx"),
  route("oracle", "routes/oracle.tsx"),
  route("puppies", "routes/puppies.tsx"),
  route("grants", "routes/grants.tsx"),
  route("match", "routes/match.tsx"),
  route("live", "routes/live.tsx"),
  route("surge", "routes/surge.tsx"),
  route("partners", "routes/partners.tsx"),
  route("roi", "routes/roi.tsx"),
  route("coach", "routes/coach.tsx"),
  route("wagpoints", "routes/wagpoints.tsx"),
  route("navigator", "routes/navigator.tsx"),
  route("ai", "routes/ai.tsx"),
  route("retreat", "routes/retreat.tsx"),
  route("gift", "routes/gift.tsx"),
  route("certify", "routes/certify.tsx"),
  route("ambassador", "routes/ambassador.tsx"),
  route("packbuilder", "routes/packbuilder.tsx"),
  route("franchise", "routes/franchise.tsx"),
  route("audio", "routes/audio.tsx"),
  route("cam", "routes/cam.tsx"),
  route("mastermind", "routes/mastermind.tsx"),
  route("subscribe", "routes/subscribe.tsx"),
  route("directory", "routes/directory.tsx"),
] satisfies RouteConfig;
